replicaCount: 1

image:
  repository: ghcr.io/federicomameli1/verdict
  tag: ba357980c29bbb57944e22ee84fe07c0bff454c9
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

env:
  openrouter_model: "z-ai/glm-4.5-air:free"
  openrouter_app_title: "Verdict"
  ci_bridge_repo: "federicomameli1/challenge-app"
