replicaCount: 1

image:
  repository: ghcr.io/federicomameli1/verdict
  tag: 2e138238b58417ddd343f87b010ed9109258c8f9
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

env:
  openrouter_model: "meta-llama/llama-3.3-70b-instruct:free"
  openrouter_app_title: "Verdict"
  ci_bridge_repo: "federicomameli1/challenge-app"
