replicaCount: 1

image:
  repository: ghcr.io/federicomameli1/verdict
  tag: 36654352493e262df8d5ac244324d91edba52484
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

env:
  openrouter_model: "z-ai/glm-4.5-air:free"
  openrouter_app_title: "Verdict"
  ci_bridge_repo: "federicomameli1/challenge-app"
